/**
 * Root layout de la aplicación.
 * Carga fuentes, aplica clases de tema y envuelve el contenido con una transición.
 */
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Transition from "./componentes/transiciones/TransitionFull"
import { ErrorBoundary } from "./componentes/utils/ErrorBoundary"
import SkipLink from "./componentes/utils/SkipLink"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preload" as="image" href="/League%20Tracker.png" fetchPriority="high" />
        <link rel="preload" as="image" href="/icon-github.svg" fetchPriority="high" />
        <link rel="preload" as="image" href="/icon-linkedin.svg" fetchPriority="high" />
        <link rel="preload" as="image" href="/icon-gmail.svg" fetchPriority="high" />
        <link rel="preload" as="image" href="/icon-linkedin-hover.svg" fetchPriority="high" />
        <link rel="preload" as="image" href="/Rodrigo.png" fetchPriority="high" />
        <link rel="preload" as="image" href="/icon-translate.svg" fetchPriority="high" />
        <link rel="preload" as="image" href="/icon-translate-hover.png" fetchPriority="high" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(){
                try {
                  var theme = localStorage.getItem('theme') || 'system';
                  var root = document.documentElement;
                  root.classList.remove('light');
                  root.classList.remove('dark');
                  if (theme === 'system') {
                    var sys = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                    root.classList.add(sys);
                  } else {
                    root.classList.add(theme);
                  }
                } catch (e) {
                  // Silently fail theme initialization - it's not critical
                  // Error will be handled by useTheme hook on client side
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SkipLink />
        <ErrorBoundary>
          <div className="min-h-screen">
            <Transition className="bg-neutral-900 dark:bg-white">{children}</Transition>
          </div>
        </ErrorBoundary>
      </body>
    </html>
  )
}